### ISSUE TITLE
请求添加code-server

### ISSUE THREAD

**Issue by Tianjie-Wu** [featurize/app-request#1]
**是否是开源软件**

是

**如果是开源软件，请贴出其 Repo 地址**

https://github.com/coder/code-server

**若是你自己的想法，请详细描述遇到的困难，以及希望的解决方式**

在我使用python构建人工智能模型并训练之前，常常需要对数据进行预处理
大多数预处理数据的程序是fortran，因此code-server会更容易处理类似的代码
因此想请featurize考虑将code-server作为应用市场的一个选项，谢谢

**其他备注**

**Comment by louis-she** [comment]
@pengbo0054

**Comment by pengbo0054** [comment]
> **是否是开源软件**
> 
> 是
> 
> **如果是开源软件，请贴出其 Repo 地址**
> 
> https://github.com/coder/code-server
> 
> **若是你自己的想法，请详细描述遇到的困难，以及希望的解决方式**
> 
> 在我使用python构建人工智能模型并训练之前，常常需要对数据进行预处理 大多数预处理数据的程序是fortran，因此code-server会更容易处理类似的代码 因此想请featurize考虑将code-server作为应用市场的一个选项，谢谢
> 
> **其他备注**

已经添加到 App 市场，欢迎测试使用。
